vitepress deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,20 +20,15 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-          path: wiki
       - name: Print working directory
         run: |
             echo "$(pwd)"
-            ls -l package.json # 确认文件存在
-      # - name: 切换到 wiki 目录
-      #   run: |
-      #     cd wiki
-      # - name: Check for package.json
-      #   run: |
-      #     if [ ! -f "package.json" ]; then
-      #       echo "package.json not found"
-      #       exit 1
-      #     fi
+      - name: Check for package.json
+        run: |
+          if [ ! -f "package.json" ]; then
+            echo "package.json not found"
+            exit 1
+          fi
       - name: 安装 PNPM
         uses: pnpm/action-setup@v3
       - name: Setup Node
